project:
  type: website
  output-dir: docs

website:
  title: "Statistique avancee en biologie -- Advanced Statistics in Ecology"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

