project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Modèles hiérarchiques pour les sciences de la vie"
  navbar:
    left:
      - href: index.qmd
        text: Course material
    right:
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

