project:
  type: website
  output-dir: docs

website:
  title: "Modèles hiérarchiques pour les sciences de la vie"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

